general.import = ["~/.cache/wal/colors-alacritty.toml"]

[window]
opacity = 1
padding = { x = 40, y = 40 }
dynamic_title = false

[font]
normal = { family = "Monocraft", style = "Bold" }
size = 12.0

[scrolling]
history = 10000
multiplier = 3

[cursor]
style = { shape = "Block", blinking = "On" }

[selection]
save_to_clipboard = true
